stages:
  - test
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  IMAGE_NAME: "registry.example.com/your-username/fastapi-app"

cache:
  paths:
    - .cache/pip

before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest
  artifacts:
    paths:
      - htmlcov/
    expire_in: 1 week

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .

deploy:
  stage: deploy
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin registry.example.com
    - docker push $IMAGE_NAME
  only:
    - main
  when: on_success
