name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and generate coverage reports
        id: tests
        continue-on-error: true
        run: |
          pytest || echo "TESTS_FAILED=true" >> $GITHUB_ENV

      - name: Upload HTML coverage report
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          name: html-coverage-report
          path: htmlcov

      - name: Fail job if tests or coverage failed
        if: env.TESTS_FAILED == 'true'
        run: exit 1
      
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/hellofastapi:latest .

      - name: Login and push Docker image to GHCR (only on main)
        if: github.ref_name == 'main'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/hellofastapi:latest
